<?php


/**
 * Base class that represents a query for the 'product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Thu Nov 25 10:25:19 2010
 *
 * @method     ProductQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     ProductQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     ProductQuery orderByCategoryId($order = Criteria::ASC) Order by the category_id column
 * @method     ProductQuery orderByPrice($order = Criteria::ASC) Order by the price column
 * @method     ProductQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     ProductQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method     ProductQuery orderBySlug($order = Criteria::ASC) Order by the slug column
 *
 * @method     ProductQuery groupById() Group by the id column
 * @method     ProductQuery groupByName() Group by the name column
 * @method     ProductQuery groupByCategoryId() Group by the category_id column
 * @method     ProductQuery groupByPrice() Group by the price column
 * @method     ProductQuery groupByCreatedAt() Group by the created_at column
 * @method     ProductQuery groupByUpdatedAt() Group by the updated_at column
 * @method     ProductQuery groupBySlug() Group by the slug column
 *
 * @method     ProductQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     ProductQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     ProductQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     ProductQuery leftJoinCategory($relationAlias = null) Adds a LEFT JOIN clause to the query using the Category relation
 * @method     ProductQuery rightJoinCategory($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Category relation
 * @method     ProductQuery innerJoinCategory($relationAlias = null) Adds a INNER JOIN clause to the query using the Category relation
 *
 * @method     Product findOne(PropelPDO $con = null) Return the first Product matching the query
 * @method     Product findOneOrCreate(PropelPDO $con = null) Return the first Product matching the query, or a new Product object populated from the query conditions when no match is found
 *
 * @method     Product findOneById(int $id) Return the first Product filtered by the id column
 * @method     Product findOneByName(string $name) Return the first Product filtered by the name column
 * @method     Product findOneByCategoryId(int $category_id) Return the first Product filtered by the category_id column
 * @method     Product findOneByPrice(double $price) Return the first Product filtered by the price column
 * @method     Product findOneByCreatedAt(string $created_at) Return the first Product filtered by the created_at column
 * @method     Product findOneByUpdatedAt(string $updated_at) Return the first Product filtered by the updated_at column
 * @method     Product findOneBySlug(string $slug) Return the first Product filtered by the slug column
 *
 * @method     array findById(int $id) Return Product objects filtered by the id column
 * @method     array findByName(string $name) Return Product objects filtered by the name column
 * @method     array findByCategoryId(int $category_id) Return Product objects filtered by the category_id column
 * @method     array findByPrice(double $price) Return Product objects filtered by the price column
 * @method     array findByCreatedAt(string $created_at) Return Product objects filtered by the created_at column
 * @method     array findByUpdatedAt(string $updated_at) Return Product objects filtered by the updated_at column
 * @method     array findBySlug(string $slug) Return Product objects filtered by the slug column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseProductQuery extends ModelCriteria
{

  /**
   * Initializes internal state of BaseProductQuery object.
   *
   * @param     string $dbName The dabase name
   * @param     string $modelName The phpName of a model, e.g. 'Book'
   * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
   */
  public function __construct($dbName = 'propel', $modelName = 'Product', $modelAlias = null)
  {
    parent::__construct($dbName, $modelName, $modelAlias);
  }

  /**
   * Returns a new ProductQuery object.
   *
   * @param     string $modelAlias The alias of a model in the query
   * @param     Criteria $criteria Optional Criteria to build the query from
   *
   * @return    ProductQuery
   */
  public static function create($modelAlias = null, $criteria = null)
  {
    if ($criteria instanceof ProductQuery)
    {
      return $criteria;
    }
    $query = new ProductQuery();
    if (null !== $modelAlias)
    {
      $query->setModelAlias($modelAlias);
    }
    if ($criteria instanceof Criteria)
    {
      $query->mergeWith($criteria);
    }
    return $query;
  }

  /**
   * Find object by primary key
   * Use instance pooling to avoid a database query if the object exists
   * <code>
   * $obj  = $c->findPk(12, $con);
   * </code>
   * @param     mixed $key Primary key to use for the query
   * @param     PropelPDO $con an optional connection object
   *
   * @return    Product|array|mixed the result, formatted by the current formatter
   */
  public function findPk($key, $con = null)
  {
    if ((null !== ($obj = ProductPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter())
    {
      // the object is alredy in the instance pool
      return $obj;
    }
    else
    {
      // the object has not been requested yet, or the formatter is not an object formatter
      $criteria = $this->isKeepQuery() ? clone $this : $this;
      $stmt = $criteria
        ->filterByPrimaryKey($key)
        ->getSelectStatement($con);
      return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }
  }

  /**
   * Find objects by primary key
   * <code>
   * $objs = $c->findPks(array(12, 56, 832), $con);
   * </code>
   * @param     array $keys Primary keys to use for the query
   * @param     PropelPDO $con an optional connection object
   *
   * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
   */
  public function findPks($keys, $con = null)
  {  
    $criteria = $this->isKeepQuery() ? clone $this : $this;
    return $this
      ->filterByPrimaryKeys($keys)
      ->find($con);
  }

  /**
   * Filter the query by primary key
   *
   * @param     mixed $key Primary key to use for the query
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByPrimaryKey($key)
  {
    return $this->addUsingAlias(ProductPeer::ID, $key, Criteria::EQUAL);
  }

  /**
   * Filter the query by a list of primary keys
   *
   * @param     array $keys The list of primary key to use for the query
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByPrimaryKeys($keys)
  {
    return $this->addUsingAlias(ProductPeer::ID, $keys, Criteria::IN);
  }

  /**
   * Filter the query on the id column
   * 
   * @param     int|array $id The value to use as filter.
   *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterById($id = null, $comparison = null)
  {
    if (is_array($id) && null === $comparison)
    {
      $comparison = Criteria::IN;
    }
    return $this->addUsingAlias(ProductPeer::ID, $id, $comparison);
  }

  /**
   * Filter the query on the name column
   * 
   * @param     string $name The value to use as filter.
   *            Accepts wildcards (* and % trigger a LIKE)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByName($name = null, $comparison = null)
  {
    if (null === $comparison)
    {
      if (is_array($name))
      {
        $comparison = Criteria::IN;
      }
      elseif (preg_match('/[\%\*]/', $name))
      {
        $name = str_replace('*', '%', $name);
        $comparison = Criteria::LIKE;
      }
    }
    return $this->addUsingAlias(ProductPeer::NAME, $name, $comparison);
  }

  /**
   * Filter the query on the category_id column
   * 
   * @param     int|array $categoryId The value to use as filter.
   *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByCategoryId($categoryId = null, $comparison = null)
  {
    if (is_array($categoryId))
    {
      $useMinMax = false;
      if (isset($categoryId['min']))
      {
        $this->addUsingAlias(ProductPeer::CATEGORY_ID, $categoryId['min'], Criteria::GREATER_EQUAL);
        $useMinMax = true;
      }
      if (isset($categoryId['max']))
      {
        $this->addUsingAlias(ProductPeer::CATEGORY_ID, $categoryId['max'], Criteria::LESS_EQUAL);
        $useMinMax = true;
      }
      if ($useMinMax)
      {
        return $this;
      }
      if (null === $comparison)
      {
        $comparison = Criteria::IN;
      }
    }
    return $this->addUsingAlias(ProductPeer::CATEGORY_ID, $categoryId, $comparison);
  }

  /**
   * Filter the query on the price column
   * 
   * @param     double|array $price The value to use as filter.
   *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByPrice($price = null, $comparison = null)
  {
    if (is_array($price))
    {
      $useMinMax = false;
      if (isset($price['min']))
      {
        $this->addUsingAlias(ProductPeer::PRICE, $price['min'], Criteria::GREATER_EQUAL);
        $useMinMax = true;
      }
      if (isset($price['max']))
      {
        $this->addUsingAlias(ProductPeer::PRICE, $price['max'], Criteria::LESS_EQUAL);
        $useMinMax = true;
      }
      if ($useMinMax)
      {
        return $this;
      }
      if (null === $comparison)
      {
        $comparison = Criteria::IN;
      }
    }
    return $this->addUsingAlias(ProductPeer::PRICE, $price, $comparison);
  }

  /**
   * Filter the query on the created_at column
   * 
   * @param     string|array $createdAt The value to use as filter.
   *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByCreatedAt($createdAt = null, $comparison = null)
  {
    if (is_array($createdAt))
    {
      $useMinMax = false;
      if (isset($createdAt['min']))
      {
        $this->addUsingAlias(ProductPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
        $useMinMax = true;
      }
      if (isset($createdAt['max']))
      {
        $this->addUsingAlias(ProductPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
        $useMinMax = true;
      }
      if ($useMinMax)
      {
        return $this;
      }
      if (null === $comparison)
      {
        $comparison = Criteria::IN;
      }
    }
    return $this->addUsingAlias(ProductPeer::CREATED_AT, $createdAt, $comparison);
  }

  /**
   * Filter the query on the updated_at column
   * 
   * @param     string|array $updatedAt The value to use as filter.
   *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByUpdatedAt($updatedAt = null, $comparison = null)
  {
    if (is_array($updatedAt))
    {
      $useMinMax = false;
      if (isset($updatedAt['min']))
      {
        $this->addUsingAlias(ProductPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
        $useMinMax = true;
      }
      if (isset($updatedAt['max']))
      {
        $this->addUsingAlias(ProductPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
        $useMinMax = true;
      }
      if ($useMinMax)
      {
        return $this;
      }
      if (null === $comparison)
      {
        $comparison = Criteria::IN;
      }
    }
    return $this->addUsingAlias(ProductPeer::UPDATED_AT, $updatedAt, $comparison);
  }

  /**
   * Filter the query on the slug column
   * 
   * @param     string $slug The value to use as filter.
   *            Accepts wildcards (* and % trigger a LIKE)
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterBySlug($slug = null, $comparison = null)
  {
    if (null === $comparison)
    {
      if (is_array($slug))
      {
        $comparison = Criteria::IN;
      }
      elseif (preg_match('/[\%\*]/', $slug))
      {
        $slug = str_replace('*', '%', $slug);
        $comparison = Criteria::LIKE;
      }
    }
    return $this->addUsingAlias(ProductPeer::SLUG, $slug, $comparison);
  }

  /**
   * Filter the query by a related Category object
   *
   * @param     Category $category  the related object to use as filter
   * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function filterByCategory($category, $comparison = null)
  {
    return $this
      ->addUsingAlias(ProductPeer::CATEGORY_ID, $category->getId(), $comparison);
  }

  /**
   * Adds a JOIN clause to the query using the Category relation
   * 
   * @param     string $relationAlias optional alias for the relation
   * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function joinCategory($relationAlias = null, $joinType = Criteria::INNER_JOIN)
  {
    $tableMap = $this->getTableMap();
    $relationMap = $tableMap->getRelation('Category');
    
    // create a ModelJoin object for this join
    $join = new ModelJoin();
    $join->setJoinType($joinType);
    $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
    if ($previousJoin = $this->getPreviousJoin())
    {
      $join->setPreviousJoin($previousJoin);
    }
    
    // add the ModelJoin to the current object
    if($relationAlias)
    {
      $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
      $this->addJoinObject($join, $relationAlias);
    }
    else
    {
      $this->addJoinObject($join, 'Category');
    }
    
    return $this;
  }

  /**
   * Use the Category relation Category object
   *
   * @see       useQuery()
   * 
   * @param     string $relationAlias optional alias for the relation,
   *                                   to be used as main alias in the secondary query
   * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
   *
   * @return    CategoryQuery A secondary query class using the current class as primary query
   */
  public function useCategoryQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
  {
    return $this
      ->joinCategory($relationAlias, $joinType)
      ->useQuery($relationAlias ? $relationAlias : 'Category', 'CategoryQuery');
  }

  /**
   * Exclude object from result
   *
   * @param     Product $product Object to remove from the list of results
   *
   * @return    ProductQuery The current query, for fluid interface
   */
  public function prune($product = null)
  {
    if ($product)
    {
      $this->addUsingAlias(ProductPeer::ID, $product->getId(), Criteria::NOT_EQUAL);
    }
    
    return $this;
  }

  // timestampable behavior
  
  /**
   * Filter by the latest updated
   *
   * @param      int $nbDays Maximum age of the latest update in days
   *
   * @return     ProductQuery The current query, for fuid interface
   */
  public function recentlyUpdated($nbDays = 7)
  {
    return $this->addUsingAlias(ProductPeer::UPDATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
  }
  
  /**
   * Filter by the latest created
   *
   * @param      int $nbDays Maximum age of in days
   *
   * @return     ProductQuery The current query, for fuid interface
   */
  public function recentlyCreated($nbDays = 7)
  {
    return $this->addUsingAlias(ProductPeer::CREATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
  }
  
  /**
   * Order by update date desc
   *
   * @return     ProductQuery The current query, for fuid interface
   */
  public function lastUpdatedFirst()
  {
    return $this->addDescendingOrderByColumn(ProductPeer::UPDATED_AT);
  }
  
  /**
   * Order by update date asc
   *
   * @return     ProductQuery The current query, for fuid interface
   */
  public function firstUpdatedFirst()
  {
    return $this->addAscendingOrderByColumn(ProductPeer::UPDATED_AT);
  }
  
  /**
   * Order by create date desc
   *
   * @return     ProductQuery The current query, for fuid interface
   */
  public function lastCreatedFirst()
  {
    return $this->addDescendingOrderByColumn(ProductPeer::CREATED_AT);
  }
  
  /**
   * Order by create date asc
   *
   * @return     ProductQuery The current query, for fuid interface
   */
  public function firstCreatedFirst()
  {
    return $this->addAscendingOrderByColumn(ProductPeer::CREATED_AT);
  }

  // sluggable behavior
  
  /**
   * Find one object based on its slug
   * 
   * @param     string $slug The value to use as filter.
   * @param     PropelPDO $con The optional connection object
   *
   * @return    Product the result, formatted by the current formatter
   */
  public function findOneBySlug($slug, $con = null)
  {
    return $this->filterBySlug($slug)->findOne($con);
  }

}
