<?php



/**
 * Skeleton subclass for performing query and update operations on the 'product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Thu Nov 25 10:25:19 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ProductPeer extends BaseProductPeer
{

}
