<?php

/**
 * Subclass for performing query and update operations on the 'product' table.
 *
 * This class was autogenerated by Propel 1.5.3 on:
 * Thu Nov 25 10:25:19 2010
 *
 * @package    propel.generator.lib.model
 */
class ProductQuery extends BaseProductQuery
{
  /**
   * filter results
   * @param  array        $values values to filter by
   * @return ProductQuery
   */
  public function filter(array $values)
  {
    if (!empty($values['category_id']))
    {
      $this->filterByCategoryId($values['category_id']);
    }
    if (!empty($values['name']))
    {
      $this->filterByName($values['name']);
    }
    if (!empty($values['price']))
    {
      $this->filterByPrice($values['price']);
    }

    return $this->find();
  }
}
